on:
  push:
    branches:
      - master
  workflow_dispatch:
jobs:
  accurics-scan:
    runs-on: ubuntu-latest
    name: accurics-scan
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Accurics Scan
        id: accurics-scan
        uses: docker://accurics/terrascan-action:latest
        with:
          only_warn: true
          verbose: true
          webhook_url: https://app.accurics.com/v1/api/terrascan
          webhook_token: fc4f1312-115e-4e0e-b3a0-55d799229799